name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^9.0.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_portal: ^1.1.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  get: ^4.7.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  syncfusion_flutter_gauges: ^28.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env

    # Fonts
    - assets/fonts/Hauora/
    - assets/fonts/Montserrat/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Hauora
      fonts:
        - asset: assets/fonts/Hauora/Hauora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Hauora/Hauora-Light.ttf
          weight: 300
        - asset: assets/fonts/Hauora/Hauora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hauora/Hauora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hauora/Hauora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hauora/Hauora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hauora/Hauora-ExtraBold.ttf
          weight: 800